#!/bin/zsh
sxhkd &
compton &
nitrogen --restore &
./.config/polybar/launch.sh &

bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 


#! /bin/sh
export BSPWM_SCRIPTS_DIR="$HOME/scripts"
gap=0

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT-gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

#Various settings
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config borderless_monocle  true
bspc config leaf_monocle true
bspc config adaptative_raise true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child

##Color settings
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#000000"
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"
bspc config focused_private_border_color "#FFFFFF"
bspc config border_width 2

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config auto_alternate true
bspc config auto_cancel true
bspc config split_ratio         0.52

#### BSPWM coloring ####
bspc config normal_border_color		"#ffffff"
bspc config active_border_color		"#ffffff"
bspc config focused_border_color	"#ffffff"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color		"#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_LVDS-1)

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a datagrip='^3' state=floating follow=on

